name: Flutter CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  
  

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.31.0-0.1.pre
          channel: beta

      - name: Install Dependencies
        run: flutter pub get

      - name: Create `firebase_options.dart`
        run: |
          mkdir -p lib
          echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart

      - name: Create `google-services.json`
        run: |
          mkdir -p android/app
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android APKs for Multiple Architectures
        run: |
          flutter build apk --release --split-per-abi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk  
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk  
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk  
            build/app/outputs/flutter-apk/app-x86_64-release.apk  

      - name: Create GitHub Release (Pre-release)
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: true
